//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DbSurat
{

    public partial class IndexSurat : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fIndex;
        [Indexed(Name = @"Index", Unique = true)]
        [Size(255)]
        public string Index
        {
            get { return fIndex; }
            set { SetPropertyValue<string>(nameof(Index), ref fIndex, value); }
        }
        string fKeperluan;
        [Size(255)]
        public string Keperluan
        {
            get { return fKeperluan; }
            set { SetPropertyValue<string>(nameof(Keperluan), ref fKeperluan, value); }
        }
        [Association(@"SuratReferencesIndexSurat")]
        public XPCollection<Surat> Surats { get { return GetCollection<Surat>(nameof(Surats)); } }
    }

}
