//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DbSurat
{

    public partial class Pegawai : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fNama;
        [Size(255)]
        public string Nama
        {
            get { return fNama; }
            set { SetPropertyValue<string>(nameof(Nama), ref fNama, value); }
        }
        string fNip;
        [Indexed(Name = @"Nip", Unique = true)]
        [Size(255)]
        public string Nip
        {
            get { return fNip; }
            set { SetPropertyValue<string>(nameof(Nip), ref fNip, value); }
        }
        Pangkat fPangkat;
        [ColumnDbDefaultValue("0")]
        [Association(@"PegawaiReferencesPangkat")]
        public Pangkat Pangkat
        {
            get { return fPangkat; }
            set { SetPropertyValue<Pangkat>(nameof(Pangkat), ref fPangkat, value); }
        }
        [Association(@"SuratReferencesPegawai")]
        public XPCollection<Surat> Surats { get { return GetCollection<Surat>(nameof(Surats)); } }
    }

}
