//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DbSurat
{

    public partial class Surat : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        IndexSurat fIndexSurat;
        [ColumnDbDefaultValue("0")]
        [Association(@"SuratReferencesIndexSurat")]
        public IndexSurat IndexSurat
        {
            get { return fIndexSurat; }
            set { SetPropertyValue<IndexSurat>(nameof(IndexSurat), ref fIndexSurat, value); }
        }
        string fKeperluan;
        [Size(SizeAttribute.Unlimited)]
        public string Keperluan
        {
            get { return fKeperluan; }
            set { SetPropertyValue<string>(nameof(Keperluan), ref fKeperluan, value); }
        }
        int fNoSurat;
        [Indexed(Name = @"NoSurat", Unique = true)]
        public int NoSurat
        {
            get { return fNoSurat; }
            set { SetPropertyValue<int>(nameof(NoSurat), ref fNoSurat, value); }
        }
        Pegawai fPemesan;
        [ColumnDbDefaultValue("0")]
        [Association(@"SuratReferencesPegawai")]
        public Pegawai Pemesan
        {
            get { return fPemesan; }
            set { SetPropertyValue<Pegawai>(nameof(Pemesan), ref fPemesan, value); }
        }
        DateTime fTanggal;
        public DateTime Tanggal
        {
            get { return fTanggal; }
            set { SetPropertyValue<DateTime>(nameof(Tanggal), ref fTanggal, value); }
        }
    }

}
